version: '3.8'

services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile.txt
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app  
    networks:
      - app-network
    restart: always  

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile.txt
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
