version: '3.8'

services:
  prs-app:
    image: prs-template:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.txt
    environment:
      - INPUT_DIR=./data/input
      - OUTPUT_DIR=./data/output
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output  
    restart: always